### ISSUE TITLE
Questions.

### ISSUE THREAD

**Issue by UserGit-2021** [atirut-w/gta3-godot#25]
1.Will there be support for game files from ps2/xbox?
2.Will there be support for EAX by replacing it with OpenAL soft?
3.Will there be support for vice city in the future?
4.Will it replicate the gameplay from the original engine? Keeping the experience of the original.
5.Will it keep the graphics from the original in godot?

**Comment by atirutw** [comment]
1. I've experimented with Xbox textures in the past, but there were problems related to texture compression. We'll see if someone manages to make it work.
2. We will most likely be using Godot's inbuilt audio effects if possible.
3. N/A
4. See README.
5. To put it plainly, no.

**Comment by UserGit-2021** [comment]
> 1. I've experimented with Xbox textures in the past, but there were problems related to texture compression. We'll see if someone manages to make it work.
> 
>     2. We will most likely be using Godot's inbuilt audio effects if possible.
> 
>     3. N/A
> 
>     4. See README.
> 
>     5. To put it plainly, no.

I see, thanks for the answers. Then I'm not interested in the project. Good luck with the project.

**Comment by hardBSDk** [comment]
@UserGit-2021 

3 - If someone translate the GTA Vice City formats, yes.
4 - Probably, with some improvements.
